import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fieldsForType } from './fields.js';
import { buildLinks } from './links.js';
import type { Project } from './types.js';

function sortedRecord(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const key of Object.keys(input).sort()) {
    out[key] = input[key];
  }
  return out;
}

/**
 * Builds the index object. Deterministic by construction: every list is
 * sorted, every object has a fixed key order, and nothing time-dependent is
 * included.
 */
export function buildIndex(project: Project): Record<string, unknown> {
  return {
    spec_version: project.manifest.spec_version,
    project: {
      id: project.manifest.project_id,
      name: project.manifest.name,
    },
    tickets: [...project.tickets]
      .sort((a, b) => a.id.localeCompare(b.id))
      .map((t) => ({
        id: t.id,
        type: t.type,
        status: t.status,
        created: t.created,
        updated: t.updated,
        title: typeof t.fields.title === 'string' ? t.fields.title : '',
        fields: sortedRecord(t.fields),
        path: t.path,
      })),
    briefs: [...project.briefs]
      .sort((a, b) => a.path.localeCompare(b.path))
      .map((b) => ({
        id: b.id,
        summary: b.summary,
        ...(b.updated !== undefined ? { updated: b.updated } : {}),
        ...(b.review_by !== undefined ? { review_by: b.review_by } : {}),
        path: b.path,
      })),
    sessions: [...project.sessions]
      .sort((a, b) => a.id.localeCompare(b.id))
      .map((s) => ({
        id: s.id,
        ticket: s.ticket,
        actor: s.actor,
        started: s.started,
        ended: s.ended,
        commits: s.commits,
        outcome: s.outcome,
        path: s.path,
      })),
    comments: [...project.comments]
      .sort((a, b) => a.path.localeCompare(b.path))
      .map((c) => ({
        ticket: c.ticket,
        actor: c.actor,
        created: c.created,
        path: c.path,
      })),
    links: buildLinks(project),
  };
}

export function stringifyIndex(index: Record<string, unknown>): string {
  return `${JSON.stringify(index, null, 2)}\n`;
}

/** Builds BOARD.md: tickets grouped by status in workflow column order. */
export function buildBoard(project: Project): string {
  const lines: string[] = [`# ${project.manifest.name} board`, ''];
  lines.push('Generated by Lovelace from ticket frontmatter. Do not edit by hand.', '');
  for (const status of project.workflow.statuses) {
    const tickets = project.tickets
      .filter((t) => t.status === status.name)
      .sort((a, b) => a.id.localeCompare(b.id));
    lines.push(`## ${status.name} (${tickets.length})`, '');
    if (tickets.length === 0) {
      lines.push('_Empty._', '');
      continue;
    }
    lines.push('| ID | Title | Type | Assignee |');
    lines.push('| --- | --- | --- | --- |');
    for (const t of tickets) {
      const title = typeof t.fields.title === 'string' ? t.fields.title : '';
      const assignee = typeof t.fields.assignee === 'string' ? t.fields.assignee : '';
      lines.push(`| ${t.id} | ${title} | ${t.type} | ${assignee} |`);
    }
    lines.push('');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

/**
 * Writes index.json and BOARD.md. Files are only touched when content
 * changed, so watchers and Git stay quiet on no-op reindexes.
 */
export function writeIndex(project: Project): { indexPath: string; boardPath: string } {
  const indexDir = join(project.dir, project.manifest.paths.index);
  mkdirSync(indexDir, { recursive: true });
  const indexPath = join(indexDir, 'index.json');
  const boardPath = join(indexDir, 'BOARD.md');
  const indexContent = stringifyIndex(buildIndex(project));
  const boardContent = buildBoard(project);
  if (!existsSync(indexPath) || readFileSync(indexPath, 'utf8') !== indexContent) {
    writeFileSync(indexPath, indexContent);
  }
  if (!existsSync(boardPath) || readFileSync(boardPath, 'utf8') !== boardContent) {
    writeFileSync(boardPath, boardContent);
  }
  return { indexPath, boardPath };
}

/** Field definitions applicable per ticket type, for schema-driven forms. */
export function fieldCatalogue(project: Project): Record<string, ReturnType<typeof fieldsForType>> {
  const out: Record<string, ReturnType<typeof fieldsForType>> = {};
  for (const type of project.workflow.types) {
    out[type.name] = fieldsForType(project.workflow, type.name);
  }
  return out;
}
