/**
 * Integration-agnostic machinery shared by the Claude Code and OpenCode
 * installers: the Lovelace section markers, marker-delimited section
 * writing, the merge-preserving JSON read/edit helper (with its
 * malformed-JSON manual-step fallback), the shared `.lovelace/AGENTS.md`
 * instruction template and refresh, the Git `prepare-commit-msg` writer and
 * detector, and the `{ written, manual }` result shape both installers
 * return.
 */
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export interface AssetResult {
  written: string[];
  /** Steps the user must take by hand, when a file could not be written safely. */
  manual: string[];
}

export const SECTION_START = '<!-- lovelace:start -->';
export const SECTION_END = '<!-- lovelace:end -->';

/**
 * The Lovelace instruction file: every direction the agent needs, owned and
 * regenerated by Lovelace. Project specifics belong in documentation/index.md, not here.
 * Shared verbatim by every integration, so a project with more than one
 * integration installed still gets one identical copy.
 */
export function agentsMdSection(): string {
  return `${SECTION_START}
# Working in this project with Lovelace

This project's tickets, documentation and session history live in \`.lovelace/\` and are managed with Lovelace. Lovelace owns and regenerates this file; put project specifics in \`.lovelace/documentation/index.md\`, not here.

## Before you start
- Read \`.lovelace/documentation/index.md\` for the project summary and reading order.
- When working a ticket, read the ticket, its parent, its dependencies, and the last two session records referencing it.

## Where files live
- Tickets live only in \`.lovelace/tickets/\`, created and changed only through the Lovelace MCP tools.
- Project documentation lives only under \`.lovelace/documentation/\`. Write every plan, decision record, guide or other project document there. Never write project documentation to a \`docs/\` folder at the repository root or anywhere else in the application tree; files outside \`.lovelace/documentation/\` are not validated or indexed and stay invisible to the project.

## Working with tickets
- Mutate tickets only through the Lovelace MCP tools (create_ticket, update_ticket); never edit files in \`.lovelace/tickets/\` directly. Documents under \`.lovelace/documentation/\` may be edited directly.
- Every document must start with a YAML frontmatter block between \`---\` lines carrying \`id\` (a unique kebab-case slug), \`type: document\` and \`summary\` (one or two sentences). A file without this block fails validation and stays out of the project's documentation.
- Include the active ticket ID in every commit message.

## Resolving a ticket
When you finish or pause work, move the ticket with update_ticket to the status that reflects what happened: the status tagged \`agent: in_progress\` while you are actively working it, the status tagged \`agent: complete\` once it is done, or any other status defined in schema.yaml if you are pausing or handing it back. Call describe_schema to see the statuses and their agent roles; any status defined there is a legal move, there is no configured flow gating it. When a move needs explaining (for example you are handing the ticket back because you are blocked), add a comment saying what you need.

## Before you finish
- Write a session record with the log_session tool: approach, what happened, the outcome, commit SHAs, and any open questions.
${SECTION_END}
`;
}

/**
 * Writes or refreshes a marker-delimited section inside `path`, preserving
 * everything outside the markers. Creating a fresh file prefixes `header`
 * (for example a top-level heading) and pushes the bare `label`; refreshing
 * an existing section pushes `${label} (section refreshed)` only when the
 * section actually changed; appending to a file with no prior section
 * pushes `${label} (section appended)`.
 */
export function writeMarkerSection(
  path: string,
  section: string,
  result: AssetResult,
  label: string,
  header = '',
): void {
  if (!existsSync(path)) {
    writeFileSync(path, `${header}${section}`);
    result.written.push(label);
    return;
  }
  const existing = readFileSync(path, 'utf8');
  if (existing.includes(SECTION_START)) {
    const updated = existing.replace(
      new RegExp(`${SECTION_START}[\\s\\S]*?${SECTION_END}\\n?`),
      section,
    );
    if (updated !== existing) {
      writeFileSync(path, updated);
      result.written.push(`${label} (section refreshed)`);
    }
    return;
  }
  writeFileSync(path, `${existing.trimEnd()}\n\n${section}`);
  result.written.push(`${label} (section appended)`);
}

/** Refreshes (or creates) the Lovelace-owned `.lovelace/AGENTS.md` instruction file. One template, one file, shared by every integration. */
export function refreshLovelaceAgentsMd(root: string, result: AssetResult): void {
  const dir = join(root, '.lovelace');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, 'AGENTS.md');
  writeMarkerSection(path, agentsMdSection(), result, '.lovelace/AGENTS.md');
}

/**
 * Splits a `mcpCommand`/`helperCommand` string into the two shapes it can
 * take: a bare binary path (returned whole, since a Windows install
 * directory can itself contain a space) or the dev `node /path/script.js`
 * form, split into the `node` command and the script path as one argument.
 */
export function parseCommand(raw: string): { command: string; args: string[] } {
  if (raw.startsWith('node ')) {
    return { command: 'node', args: [raw.slice('node '.length).trim()] };
  }
  return { command: raw, args: [] };
}

/**
 * Reads `path` as JSON (an empty object when absent), applies `merge` to
 * fold in the Lovelace entry, and writes the pretty-printed result back,
 * always pushing `writtenLabel`. When the existing file fails to parse as
 * strict JSON, nothing is touched and `manualMessage` is pushed to
 * `result.manual` instead, mirroring the original `.mcp.json` behaviour: a
 * hand-edited but broken file is never silently clobbered.
 */
export function mergeJsonFile<T extends Record<string, unknown>>(
  path: string,
  merge: (existing: T) => T,
  result: AssetResult,
  writtenLabel: string,
  manualMessage: string,
): void {
  let config: T = {} as T;
  if (existsSync(path)) {
    try {
      config = JSON.parse(readFileSync(path, 'utf8')) as T;
    } catch {
      result.manual.push(manualMessage);
      return;
    }
  }
  const merged = merge(config);
  writeFileSync(path, `${JSON.stringify(merged, null, 2)}\n`);
  result.written.push(writtenLabel);
}

/** True when `path` exists and contains `marker` (the section start marker by default), resilient to an unreadable file. */
export function containsMarker(path: string, marker: string = SECTION_START): boolean {
  if (!existsSync(path)) return false;
  try {
    return readFileSync(path, 'utf8').includes(marker);
  } catch {
    return false;
  }
}

/**
 * Writes the opt-in `prepare-commit-msg` Git hook that injects the active
 * ticket ID into commit messages. Shared by every integration: whichever
 * installs first writes it, and each integration's detector recognises the
 * other's copy.
 */
export function writeGitHook(root: string, result: AssetResult): void {
  const hooksDir = join(root, '.git', 'hooks');
  if (!existsSync(join(root, '.git'))) {
    result.manual.push('Not a Git repository; initialise Git and re-run to install the prepare-commit-msg hook.');
    return;
  }
  mkdirSync(hooksDir, { recursive: true });
  const path = join(hooksDir, 'prepare-commit-msg');
  const script = `#!/bin/sh
# Lovelace: inject the active ticket ID into commit messages.
STATE=".lovelace/state/active_ticket"
[ -f "$STATE" ] || exit 0
TICKET=$(head -n1 "$STATE" | tr -d '[:space:]')
[ -n "$TICKET" ] || exit 0
grep -q "$TICKET" "$1" 2>/dev/null && exit 0
printf '%s (%s)\\n' "$(head -n1 "$1")" "$TICKET" > "$1.lovelace" 2>/dev/null || exit 0
tail -n +2 "$1" >> "$1.lovelace"
mv "$1.lovelace" "$1"
`;
  if (existsSync(path) && !readFileSync(path, 'utf8').includes('Lovelace')) {
    result.manual.push('.git/hooks/prepare-commit-msg already exists; append the Lovelace snippet yourself.');
    return;
  }
  writeFileSync(path, script);
  chmodSync(path, 0o755);
  result.written.push('.git/hooks/prepare-commit-msg');
}

/** True when `.git/hooks/prepare-commit-msg` exists and references Lovelace, whichever integration wrote it. */
export function detectGitHook(root: string): boolean {
  const path = join(root, '.git', 'hooks', 'prepare-commit-msg');
  if (!existsSync(path)) return false;
  try {
    return readFileSync(path, 'utf8').includes('Lovelace');
  } catch {
    return false;
  }
}
