/**
 * Writes the Claude Code assets into a user's project: the CLAUDE.md
 * section, .mcp.json, hooks in .claude/settings.json, slash commands, and
 * the opt-in prepare-commit-msg Git hook. Everything is additive: existing
 * files are appended to or merged, never overwritten.
 */
import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';

export interface ClaudeAssetOptions {
  /** Command (absolute path or name on PATH) for the MCP server binary. */
  mcpCommand: string;
  /** Command for the agent helper binary. */
  helperCommand: string;
  /** Install the prepare-commit-msg Git hook (opt-in). */
  gitHook?: boolean;
}

export interface ClaudeAssetResult {
  written: string[];
  /** Steps the user must take by hand, when a file could not be written safely. */
  manual: string[];
}

const SECTION_START = '<!-- lovelace:start -->';
const SECTION_END = '<!-- lovelace:end -->';

/**
 * The CLAUDE.md block is a pointer, not a manual: it sends the agent to the
 * Lovelace instruction file and imports it (Claude Code expands `@path`), so
 * all direction lives in one Lovelace-owned file.
 */
export function claudeMdSection(): string {
  return `${SECTION_START}
## Lovelace

This project uses Lovelace; its tickets, documents and session history live in \`.lovelace/\`. Before any work, read and follow \`.lovelace/AGENTS.md\`.

@.lovelace/AGENTS.md
${SECTION_END}
`;
}

/**
 * The Lovelace instruction file: every direction the agent needs, owned and
 * regenerated by Lovelace. Project specifics belong in documentation/index.md, not here.
 */
export function agentsMdSection(): string {
  return `${SECTION_START}
# Working in this project with Lovelace

This project's tickets, documentation and session history live in \`.lovelace/\` and are managed with Lovelace. Lovelace owns and regenerates this file; put project specifics in \`.lovelace/documentation/index.md\`, not here.

## Before you start
- Read \`.lovelace/documentation/index.md\` for the project summary and reading order.
- When working a ticket, read the ticket, its parent, its dependencies, and the last two session records referencing it.

## Working with tickets
- Mutate tickets only through the Lovelace MCP tools (create_ticket, update_ticket); never edit files in \`.lovelace/tickets/\` directly. Documents under \`.lovelace/documentation/\` may be edited directly.
- Every document must start with a YAML frontmatter block between \`---\` lines carrying \`id\` (a unique kebab-case slug), \`type: document\` and \`summary\` (one or two sentences). A file without this block fails validation and stays out of the project's documentation.
- Include the active ticket ID in every commit message.

## Resolving a ticket
When you finish or pause work, move the ticket with update_ticket to the status that reflects what happened: the status tagged \`agent: in_progress\` while you are actively working it, the status tagged \`agent: complete\` once it is done, or any other status defined in schema.yaml if you are pausing or handing it back. Call describe_schema to see the statuses and their agent roles; any status defined there is a legal move, there is no configured flow gating it. When a move needs explaining (for example you are handing the ticket back because you are blocked), add a comment saying what you need.

## Before you finish
- Write a session record with the log_session tool: approach, what happened, the outcome, commit SHAs, and any open questions.
${SECTION_END}
`;
}

function writeClaudeMd(root: string, result: ClaudeAssetResult): void {
  const path = join(root, 'CLAUDE.md');
  const section = claudeMdSection();
  if (!existsSync(path)) {
    writeFileSync(path, `# CLAUDE.md\n\n${section}`);
    result.written.push('CLAUDE.md');
    return;
  }
  const existing = readFileSync(path, 'utf8');
  if (existing.includes(SECTION_START)) {
    const updated = existing.replace(
      new RegExp(`${SECTION_START}[\\s\\S]*?${SECTION_END}\\n?`),
      section,
    );
    if (updated !== existing) {
      writeFileSync(path, updated);
      result.written.push('CLAUDE.md (section refreshed)');
    }
    return;
  }
  writeFileSync(path, `${existing.trimEnd()}\n\n${section}`);
  result.written.push('CLAUDE.md (section appended)');
}

/** Writes (or refreshes) the Lovelace-owned `.lovelace/AGENTS.md` instruction file. */
function writeAgentsMd(root: string, result: ClaudeAssetResult): void {
  const dir = join(root, '.lovelace');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, 'AGENTS.md');
  const section = agentsMdSection();
  if (!existsSync(path)) {
    writeFileSync(path, `${section}`);
    result.written.push('.lovelace/AGENTS.md');
    return;
  }
  const existing = readFileSync(path, 'utf8');
  if (existing.includes(SECTION_START)) {
    const updated = existing.replace(
      new RegExp(`${SECTION_START}[\\s\\S]*?${SECTION_END}\\n?`),
      section,
    );
    if (updated !== existing) {
      writeFileSync(path, updated);
      result.written.push('.lovelace/AGENTS.md (refreshed)');
    }
    return;
  }
  writeFileSync(path, `${existing.trimEnd()}\n\n${section}`);
  result.written.push('.lovelace/AGENTS.md (section appended)');
}

function writeMcpJson(root: string, options: ClaudeAssetOptions, result: ClaudeAssetResult): void {
  const path = join(root, '.mcp.json');
  // "node /path/server.js" style commands split into command plus args.
  const [command = '', ...args] = options.mcpCommand.split(' ');
  const entry = {
    command,
    args,
    env: { LOVELACE_ROOT: '.' },
  };
  let config: { mcpServers?: Record<string, unknown> } = {};
  if (existsSync(path)) {
    try {
      config = JSON.parse(readFileSync(path, 'utf8')) as typeof config;
    } catch {
      result.manual.push(
        `.mcp.json exists but is not valid JSON; add a "lovelace" entry yourself: ${JSON.stringify({ lovelace: entry })}`,
      );
      return;
    }
  }
  config.mcpServers = { ...config.mcpServers, lovelace: entry };
  writeFileSync(path, `${JSON.stringify(config, null, 2)}\n`);
  result.written.push('.mcp.json');
}

function writeHooks(root: string, options: ClaudeAssetOptions, result: ClaudeAssetResult): void {
  const dir = join(root, '.claude');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, 'settings.json');
  let settings: Record<string, unknown> = {};
  if (existsSync(path)) {
    try {
      settings = JSON.parse(readFileSync(path, 'utf8')) as Record<string, unknown>;
    } catch {
      result.manual.push('.claude/settings.json exists but is not valid JSON; add the Lovelace hooks by hand (see docs).');
      return;
    }
  }
  const helper = options.helperCommand;
  const hooks = (settings.hooks ?? {}) as Record<string, unknown[]>;
  const ensure = (event: string, matcher: string | undefined, command: string) => {
    const list = (hooks[event] ?? []) as Array<{ matcher?: string; hooks: Array<{ command: string }> }>;
    const exists = list.some((h) => h.hooks?.some((x) => x.command === command));
    if (!exists) {
      const entry: { matcher?: string; hooks: Array<{ type: string; command: string }> } = {
        hooks: [{ type: 'command', command }],
      };
      if (matcher !== undefined) entry.matcher = matcher;
      list.push(entry);
    }
    hooks[event] = list;
  };
  // Migration (ADR-0012): older installs also fired presence-clear on Stop.
  // session-check now folds that clear in when a stop passes, so a
  // leftover Stop entry is stale; strip it, leaving any other Stop hook
  // (including one a user added by hand) untouched. SessionEnd keeps its
  // own presence-clear entry below. Idempotent: nothing to strip once
  // removed.
  if (Array.isArray(hooks.Stop)) {
    hooks.Stop = (hooks.Stop as Array<{ matcher?: string; hooks: Array<{ command: string }> }>).filter(
      (entry) => !entry.hooks?.every((h) => h.command?.endsWith(' presence-clear')),
    );
  }
  ensure('SessionStart', undefined, `${helper} digest`);
  ensure('Stop', undefined, `${helper} session-check`);
  ensure('PreToolUse', 'Edit|Write', `${helper} guard`);
  // The live-agent marker: written at turn start, cleared when a passing
  // stop lets the turn end or the session ends outright (ADR-0012).
  ensure('UserPromptSubmit', undefined, `${helper} presence-start`);
  ensure('SessionEnd', undefined, `${helper} presence-clear`);
  // Per-session active-ticket marker, so concurrent sessions do not share
  // the singleton slot that session-check enforces on Stop.
  ensure('PostToolUse', 'mcp__lovelace__set_active_ticket', `${helper} track-active`);
  // The heartbeat: refreshes every session's presence entry on every tool
  // call, so the ring survives between prompts without relying on a
  // started_at that never moves.
  ensure('PostToolUse', undefined, `${helper} presence-beat`);
  settings.hooks = hooks;
  writeFileSync(path, `${JSON.stringify(settings, null, 2)}\n`);
  result.written.push('.claude/settings.json');
}

function writeCommands(root: string, result: ClaudeAssetResult): void {
  const dir = join(root, '.claude', 'commands');
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    join(dir, 'ticket.md'),
    `---
description: Load a Lovelace ticket into context and start working it
---

Work Lovelace ticket $ARGUMENTS:

1. Use the Lovelace query_tickets tool to load the ticket, then read its parent and every ticket in depends_on.
2. Use read_document on .lovelace/documentation/index.md and any documents the ticket references.
3. Use search to find the last two session records referencing this ticket and read their open questions.
4. Call set_active_ticket with the ticket ID.
5. If the ticket is not already in progress, move it with update_ticket to the status tagged \`agent: in_progress\`.
6. Summarise the ticket, its acceptance criteria and any open questions, then begin.
`,
  );
  writeFileSync(
    join(dir, 'done.md'),
    `---
description: Close out the active Lovelace ticket
---

Finish the active Lovelace ticket:

1. Read .lovelace/state/active_ticket for the active ticket ID; if empty, ask which ticket to close.
2. Re-read the ticket's acceptance criteria and check each one against what you actually did.
3. Move the ticket with update_ticket to the status tagged \`agent: complete\` if the work is done, or another status defined in schema.yaml that reflects the outcome. If you are handing it back, add a comment explaining what you need.
4. Write the session record with log_session: approach, what happened, outcome, commit SHAs, open questions.
5. Call set_active_ticket with null to clear it.
`,
  );
  result.written.push('.claude/commands/ticket.md', '.claude/commands/done.md');
}

function writeGitHook(root: string, result: ClaudeAssetResult): void {
  const hooksDir = join(root, '.git', 'hooks');
  if (!existsSync(join(root, '.git'))) {
    result.manual.push('Not a Git repository; initialise Git and re-run to install the prepare-commit-msg hook.');
    return;
  }
  mkdirSync(hooksDir, { recursive: true });
  const path = join(hooksDir, 'prepare-commit-msg');
  const script = `#!/bin/sh
# Lovelace: inject the active ticket ID into commit messages.
STATE=".lovelace/state/active_ticket"
[ -f "$STATE" ] || exit 0
TICKET=$(head -n1 "$STATE" | tr -d '[:space:]')
[ -n "$TICKET" ] || exit 0
grep -q "$TICKET" "$1" 2>/dev/null && exit 0
printf '%s (%s)\\n' "$(head -n1 "$1")" "$TICKET" > "$1.lovelace" 2>/dev/null || exit 0
tail -n +2 "$1" >> "$1.lovelace"
mv "$1.lovelace" "$1"
`;
  if (existsSync(path) && !readFileSync(path, 'utf8').includes('Lovelace')) {
    result.manual.push('.git/hooks/prepare-commit-msg already exists; append the Lovelace snippet yourself.');
    return;
  }
  writeFileSync(path, script);
  chmodSync(path, 0o755);
  result.written.push('.git/hooks/prepare-commit-msg');
}

export interface ClaudeInstallStatus {
  /** True when all three core pieces are present: mcp, hooks, commands. */
  installed: boolean;
  /** `.lovelace/AGENTS.md` exists with the Lovelace section. */
  agentsMd: boolean;
  /** `CLAUDE.md` contains the Lovelace section marker. */
  claudeMd: boolean;
  /** `.mcp.json` exists with an `mcpServers.lovelace` entry. */
  mcp: boolean;
  /** `.claude/settings.json` exists with Lovelace hook commands. */
  hooks: boolean;
  /** `.claude/commands/ticket.md` exists. */
  commands: boolean;
  /** `.git/hooks/prepare-commit-msg` exists and references Lovelace. */
  gitHook: boolean;
}

const KNOWN_HELPER_SUFFIXES = [' digest', 'session-check', ' guard', 'presence-start', 'presence-clear', 'presence-beat', 'track-active'];

/**
 * Inspects on-disk assets to determine whether the Claude Code integration
 * has been installed for the given project root. Read-only and resilient to
 * malformed JSON (treats as not present rather than throwing).
 */
export function detectClaudeAssets(root: string): ClaudeInstallStatus {
  let mcp = false;
  const mcpPath = join(root, '.mcp.json');
  if (existsSync(mcpPath)) {
    try {
      const raw = JSON.parse(readFileSync(mcpPath, 'utf8')) as { mcpServers?: Record<string, unknown> };
      mcp = typeof raw.mcpServers === 'object' && raw.mcpServers !== null && 'lovelace' in raw.mcpServers;
    } catch {
      // malformed JSON: treat as not present
    }
  }

  let hooks = false;
  const settingsPath = join(root, '.claude', 'settings.json');
  if (existsSync(settingsPath)) {
    try {
      const raw = JSON.parse(readFileSync(settingsPath, 'utf8')) as { hooks?: unknown };
      if (raw.hooks) {
        const flat = JSON.stringify(raw.hooks);
        hooks = KNOWN_HELPER_SUFFIXES.some((suffix) => flat.includes(suffix));
      }
    } catch {
      // malformed JSON: treat as not present
    }
  }

  const commands = existsSync(join(root, '.claude', 'commands', 'ticket.md'));

  let agentsMd = false;
  const agentsPath = join(root, '.lovelace', 'AGENTS.md');
  if (existsSync(agentsPath)) {
    try {
      agentsMd = readFileSync(agentsPath, 'utf8').includes(SECTION_START);
    } catch {
      agentsMd = true;
    }
  }

  let claudeMd = false;
  const claudeMdPath = join(root, 'CLAUDE.md');
  if (existsSync(claudeMdPath)) {
    try {
      claudeMd = readFileSync(claudeMdPath, 'utf8').includes(SECTION_START);
    } catch {
      // treat as not present
    }
  }

  let gitHook = false;
  const gitHookPath = join(root, '.git', 'hooks', 'prepare-commit-msg');
  if (existsSync(gitHookPath)) {
    try {
      gitHook = readFileSync(gitHookPath, 'utf8').includes('Lovelace');
    } catch {
      // treat as not present
    }
  }

  return {
    installed: mcp && hooks && commands,
    agentsMd,
    claudeMd,
    mcp,
    hooks,
    commands,
    gitHook,
  };
}

export function installClaudeAssets(root: string, options: ClaudeAssetOptions): ClaudeAssetResult {
  const result: ClaudeAssetResult = { written: [], manual: [] };
  writeAgentsMd(root, result);
  writeClaudeMd(root, result);
  writeMcpJson(root, options, result);
  writeHooks(root, options, result);
  writeCommands(root, result);
  if (options.gitHook) writeGitHook(root, result);
  return result;
}
